### ISSUE TITLE
Invitation to try out the new client + publishing to Crates.io

### ISSUE THREAD

**Issue by miraclx** [bicarus-labs/near-api-rs#1]
Hey there!

So, I noticed you extracted the `near-jsonrpc-client` from `nearcore`, touched it up a little, and made it into this `near-api-rs` crate, which is super cool.

I'd like to point out that we are migrating off of that design to a properly typed client with better error handling. A client that is generally better-built and could ease the experience for the community. We initially believed that would later evolve into `near-api-rs`, but later resolved to decouple the lower-level client from the higher-level API interface. So far, a ton of work has been done in that regard, and meticulously so.

You should check it out: https://github.com/near/near-jsonrpc-client-rs

On the path to making all this work we've accomplished, easily and generally accessible, we decided to call it and publish them on crates.io, so the community could experiment with them, and we could iterate quicker. That's when I noticed you had already done so. Amazing really, thanks for the initiative.

However, over the past couple of days, we have set infrastructure in place to automate publishing alongside `nearcore` releases, ensuring they're published promptly and are always up-to-date. Although, we can no longer proceed with that because the crates have now been claimed under your domain. In that regard, it would be amazing if we could come to an understanding and have those crates transferred [over to us](https://crates.io/users/nearprotocol-ci), so we can take over that responsibility.

Thank you for understanding, and yeah, I invite you to experiment with the new client in whatever it is you're building. See how well it works for you. And better still, contribute to it; your contributions are absolutely welcome anytime.

**Comment by frol** [comment]
cc @bicarus-labs @phanletrunghieu

**Comment by roycephan** [comment]
This package is edited to compatible with `tokio`.

If you are used to using actix-web, you can use https://github.com/near/near-jsonrpc-client-rs. If you want to use it with tokio, you can use this.

**Comment by roycephan** [comment]
I'll move packages that have name conflict with `nearcore` in crate to you.

**Comment by miraclx** [comment]
Hi, @phanletrunghieu, https://github.com/near/near-jsonrpc-client-rs is indeed compatible with tokio (see example in the tests https://github.com/near/near-jsonrpc-client-rs/blob/75363a806a9dc48b72f05ad3ee4bf85a982028ba/src/lib.rs#L350-L351).
